// Dev Seed for Kaya EMR
// Populates Dexie with 40 patients, 7 historical visits, and prescriptions for local dev.

import { db, DbPatient, DbVisit, Prescription } from './db';

export const DEV_PATIENTS: DbPatient[] = [
  {
    id: 'P-0412',
    clinicId: 'P-0412',
    external_id: 'P-0412',
    fullName: 'Sunita Patil',
    full_name: 'Sunita Patil',
    age: 42,
    gender: 'Female',
    village: 'Wardha',
    phone: '+91 98721 00412',
    allergies: 'Penicillin allergy',
    chronicConditions: 'Type 2 Diabetes, Essential Hypertension',
    alerts: [
      { id: 'a1', label: 'Penicillin allergy', type: 'danger' },
      { id: 'a2', label: 'Diabetic', type: 'warning' },
    ],
    registeredDate: '2023-03-14',
    firstSeenDate: '14 Mar 2023',
    lastVisitDate: '2026-09-14',
    lastVisitRelative: '6 days ago',
    totalVisits: 7,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'P-0000',
    clinicId: 'P-0000',
    external_id: 'P-0000',
    fullName: 'Kamla Bai',
    full_name: 'Kamla Bai',
    age: 36,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '+91 94220 00018',
    allergies: undefined,
    alerts: [],
    registeredDate: '2026-09-19',
    firstSeenDate: '19 Sep 2026',
    lastVisitDate: undefined,
    lastVisitRelative: 'Never',
    totalVisits: 0,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-1',
    clinicId: 'KAY-26-0104',
    external_id: 'KAY-26-0104',
    nationalId: '9842-1049-5512',
    fullName: 'Anandi Devi',
    full_name: 'Anandi Devi',
    age: 48,
    gender: 'Female',
    village: 'Rampur',
    phone: '98721 44320',
    bloodGroup: 'B+',
    allergies: 'Penicillin (mild rash)',
    chronicConditions: 'Essential Hypertension',
    emergencyContactName: 'Mohan Lal (Husband)',
    emergencyContactPhone: '98721 44321',
    registeredDate: '2026-01-14',
    lastVisitDate: '2026-09-19',
    totalVisits: 6,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-2',
    clinicId: 'KAY-26-0105',
    external_id: 'KAY-26-0105',
    nationalId: '3310-8429-1190',
    fullName: 'Bikram Mondal',
    full_name: 'Bikram Mondal',
    age: 34,
    gender: 'Male',
    village: 'Sundarpur',
    phone: '94331 87219',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    emergencyContactName: 'Kalyani Mondal',
    emergencyContactPhone: '94331 87220',
    registeredDate: '2026-03-02',
    lastVisitDate: '2026-09-19',
    totalVisits: 3,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-3',
    clinicId: 'KAY-26-0106',
    external_id: 'KAY-26-0106',
    nationalId: '7721-0043-9821',
    fullName: 'Pooja Soren',
    full_name: 'Pooja Soren',
    age: 23,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97320 11984',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'Primigravida (28 weeks gestation)',
    emergencyContactName: 'Birsa Soren',
    emergencyContactPhone: '97320 11985',
    registeredDate: '2026-05-18',
    lastVisitDate: '2026-09-19',
    totalVisits: 4,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-4',
    clinicId: 'KAY-26-0107',
    external_id: 'KAY-26-0107',
    nationalId: '4491-3820-7419',
    fullName: 'Gopal Chandra Das',
    full_name: 'Gopal Chandra Das',
    age: 62,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98302 99411',
    bloodGroup: 'AB+',
    allergies: 'Sulfa drugs',
    chronicConditions: 'Type 2 Diabetes Mellitus, Mild Osteoarthritis',
    emergencyContactName: 'Rabin Das',
    emergencyContactPhone: '98302 99412',
    registeredDate: '2025-11-09',
    lastVisitDate: '2026-09-18',
    totalVisits: 11,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-5',
    clinicId: 'KAY-26-0108',
    external_id: 'KAY-26-0108',
    fullName: 'Meena Kumari',
    full_name: 'Meena Kumari',
    age: 7,
    gender: 'Female',
    village: 'Rampur',
    phone: '98721 00219',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    emergencyContactName: 'Shanti Devi',
    emergencyContactPhone: '98721 00219',
    registeredDate: '2026-08-11',
    lastVisitDate: '2026-09-19',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-6',
    clinicId: 'KAY-26-0109',
    external_id: 'KAY-26-0109',
    nationalId: '1182-9931-4501',
    fullName: 'Tarun Karmakar',
    full_name: 'Tarun Karmakar',
    age: 29,
    gender: 'Male',
    village: 'Dholpur',
    phone: '98311 44520',
    bloodGroup: 'B+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-09-01',
    lastVisitDate: '2026-09-15',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-7',
    clinicId: 'KAY-26-0110',
    external_id: 'KAY-26-0110',
    fullName: 'Lakshmi Soren',
    full_name: 'Lakshmi Soren',
    age: 55,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97320 88219',
    bloodGroup: 'O-',
    allergies: 'NSAIDs',
    chronicConditions: 'Chronic Bronchitis',
    registeredDate: '2026-02-20',
    lastVisitDate: '2026-09-10',
    totalVisits: 5,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-8',
    clinicId: 'KAY-26-0111',
    external_id: 'KAY-26-0111',
    fullName: 'Raju Shinde',
    full_name: 'Raju Shinde',
    age: 38,
    gender: 'Male',
    village: 'Wardha',
    phone: '98220 11922',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-04-12',
    lastVisitDate: '2026-09-08',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-9',
    clinicId: 'KAY-26-0112',
    external_id: 'KAY-26-0112',
    fullName: 'Geeta Deshmukh',
    full_name: 'Geeta Deshmukh',
    age: 50,
    gender: 'Female',
    village: 'Wardha',
    phone: '98221 44389',
    bloodGroup: 'B+',
    allergies: 'Aspirin',
    chronicConditions: 'Hypertension',
    registeredDate: '2025-08-19',
    lastVisitDate: '2026-09-01',
    totalVisits: 8,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-10',
    clinicId: 'KAY-26-0113',
    external_id: 'KAY-26-0113',
    fullName: 'Devendra Yadav',
    full_name: 'Devendra Yadav',
    age: 45,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98930 11204',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'Chronic Gastritis',
    registeredDate: '2026-01-05',
    lastVisitDate: '2026-08-28',
    totalVisits: 3,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-11',
    clinicId: 'KAY-26-0114',
    external_id: 'KAY-26-0114',
    fullName: 'Savitri Bai',
    full_name: 'Savitri Bai',
    age: 68,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97321 00982',
    bloodGroup: 'AB-',
    allergies: 'None reported',
    chronicConditions: 'Cataract, Generalized Osteoarthritis',
    registeredDate: '2024-11-20',
    lastVisitDate: '2026-08-14',
    totalVisits: 14,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-12',
    clinicId: 'KAY-26-0115',
    external_id: 'KAY-26-0115',
    fullName: 'Mahesh Gaikwad',
    full_name: 'Mahesh Gaikwad',
    age: 26,
    gender: 'Male',
    village: 'Sundarpur',
    phone: '94330 55198',
    bloodGroup: 'A-',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-07-02',
    lastVisitDate: '2026-07-20',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-13',
    clinicId: 'KAY-26-0116',
    external_id: 'KAY-26-0116',
    fullName: 'Parvati Murmu',
    full_name: 'Parvati Murmu',
    age: 31,
    gender: 'Female',
    village: 'Dholpur',
    phone: '98319 77210',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'Lactating Mother (4 months infant)',
    registeredDate: '2025-10-14',
    lastVisitDate: '2026-08-30',
    totalVisits: 6,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-14',
    clinicId: 'KAY-26-0117',
    external_id: 'KAY-26-0117',
    fullName: 'Sanjay Boro',
    full_name: 'Sanjay Boro',
    age: 40,
    gender: 'Male',
    village: 'Rampur',
    phone: '98722 33819',
    bloodGroup: 'B+',
    allergies: 'Sulphonamides',
    chronicConditions: 'Recurrent Nephrolithiasis',
    registeredDate: '2026-02-18',
    lastVisitDate: '2026-08-05',
    totalVisits: 4,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-15',
    clinicId: 'KAY-26-0118',
    external_id: 'KAY-26-0118',
    fullName: 'Radhika Mandi',
    full_name: 'Radhika Mandi',
    age: 19,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97320 44921',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'Moderate Anemia',
    registeredDate: '2026-06-11',
    lastVisitDate: '2026-08-18',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-16',
    clinicId: 'KAY-26-0119',
    external_id: 'KAY-26-0119',
    fullName: 'Ashok Kumar Shaw',
    full_name: 'Ashok Kumar Shaw',
    age: 58,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98305 11900',
    bloodGroup: 'A+',
    allergies: 'Penicillin',
    chronicConditions: 'Type 2 Diabetes, Ischemic Heart Disease',
    registeredDate: '2025-05-22',
    lastVisitDate: '2026-09-02',
    totalVisits: 10,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-17',
    clinicId: 'KAY-26-0120',
    external_id: 'KAY-26-0120',
    fullName: 'Urmila Khatun',
    full_name: 'Urmila Khatun',
    age: 27,
    gender: 'Female',
    village: 'Sundarpur',
    phone: '94338 00192',
    bloodGroup: 'B-',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-03-30',
    lastVisitDate: '2026-08-12',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-18',
    clinicId: 'KAY-26-0121',
    external_id: 'KAY-26-0121',
    fullName: 'Subhash Mahato',
    full_name: 'Subhash Mahato',
    age: 52,
    gender: 'Male',
    village: 'Dholpur',
    phone: '98315 22918',
    bloodGroup: 'AB+',
    allergies: 'None reported',
    chronicConditions: 'COPD (Beedi smoker)',
    registeredDate: '2025-12-04',
    lastVisitDate: '2026-09-05',
    totalVisits: 8,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-19',
    clinicId: 'KAY-26-0122',
    external_id: 'KAY-26-0122',
    fullName: 'Kusum Hembram',
    full_name: 'Kusum Hembram',
    age: 35,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97325 66100',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'Hypothyroidism',
    registeredDate: '2025-09-15',
    lastVisitDate: '2026-07-29',
    totalVisits: 5,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-20',
    clinicId: 'KAY-26-0123',
    external_id: 'KAY-26-0123',
    fullName: 'Dilip Sarkar',
    full_name: 'Dilip Sarkar',
    age: 64,
    gender: 'Male',
    village: 'Rampur',
    phone: '98728 99102',
    bloodGroup: 'B+',
    allergies: 'Iodine contrast',
    chronicConditions: 'Benign Prostatic Hyperplasia (BPH)',
    registeredDate: '2025-04-10',
    lastVisitDate: '2026-08-20',
    totalVisits: 7,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-21',
    clinicId: 'KAY-26-0124',
    external_id: 'KAY-26-0124',
    fullName: 'Shobha Rani Biswas',
    full_name: 'Shobha Rani Biswas',
    age: 49,
    gender: 'Female',
    village: 'Sundarpur',
    phone: '94334 11802',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'Dyslipidemia',
    registeredDate: '2026-01-28',
    lastVisitDate: '2026-08-15',
    totalVisits: 3,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-22',
    clinicId: 'KAY-26-0125',
    external_id: 'KAY-26-0125',
    fullName: 'Nilesh Rathod',
    full_name: 'Nilesh Rathod',
    age: 22,
    gender: 'Male',
    village: 'Wardha',
    phone: '98229 00812',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-05-09',
    lastVisitDate: '2026-07-10',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-23',
    clinicId: 'KAY-26-0126',
    external_id: 'KAY-26-0126',
    fullName: 'Champa Tudu',
    full_name: 'Champa Tudu',
    age: 46,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97328 11029',
    bloodGroup: 'B-',
    allergies: 'Ciprofloxacin',
    chronicConditions: 'Rheumatoid Arthritis',
    registeredDate: '2025-07-11',
    lastVisitDate: '2026-08-25',
    totalVisits: 9,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-24',
    clinicId: 'KAY-26-0127',
    external_id: 'KAY-26-0127',
    fullName: 'Kishore Paul',
    full_name: 'Kishore Paul',
    age: 39,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98309 44101',
    bloodGroup: 'O-',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-02-14',
    lastVisitDate: '2026-06-30',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-25',
    clinicId: 'KAY-26-0128',
    external_id: 'KAY-26-0128',
    fullName: 'Anita Kulkarni',
    full_name: 'Anita Kulkarni',
    age: 53,
    gender: 'Female',
    village: 'Wardha',
    phone: '98224 88301',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'Type 2 Diabetes',
    registeredDate: '2025-06-03',
    lastVisitDate: '2026-09-04',
    totalVisits: 11,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-26',
    clinicId: 'KAY-26-0129',
    external_id: 'KAY-26-0129',
    fullName: 'Basanti Roy',
    full_name: 'Basanti Roy',
    age: 60,
    gender: 'Female',
    village: 'Rampur',
    phone: '98725 11928',
    bloodGroup: 'B+',
    allergies: 'None reported',
    chronicConditions: 'Hypertension, Left Ventricular Hypertrophy',
    registeredDate: '2025-03-21',
    lastVisitDate: '2026-08-19',
    totalVisits: 8,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-27',
    clinicId: 'KAY-26-0130',
    external_id: 'KAY-26-0130',
    fullName: 'Pradip Samanta',
    full_name: 'Pradip Samanta',
    age: 44,
    gender: 'Male',
    village: 'Sundarpur',
    phone: '94336 77201',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'Fatty Liver Grade 1',
    registeredDate: '2026-03-15',
    lastVisitDate: '2026-07-22',
    totalVisits: 3,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-28',
    clinicId: 'KAY-26-0131',
    external_id: 'KAY-26-0131',
    fullName: 'Suniti Hansda',
    full_name: 'Suniti Hansda',
    age: 28,
    gender: 'Female',
    village: 'Dholpur',
    phone: '98314 99018',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-06-01',
    lastVisitDate: '2026-08-01',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-29',
    clinicId: 'KAY-26-0132',
    external_id: 'KAY-26-0132',
    fullName: 'Govind Rao',
    full_name: 'Govind Rao',
    age: 71,
    gender: 'Male',
    village: 'Wardha',
    phone: '98226 33902',
    bloodGroup: 'O+',
    allergies: 'Beta blockers',
    chronicConditions: 'Chronic Kidney Disease Stage 3a',
    registeredDate: '2024-09-12',
    lastVisitDate: '2026-09-06',
    totalVisits: 15,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-30',
    clinicId: 'KAY-26-0133',
    external_id: 'KAY-26-0133',
    fullName: 'Madhuri Karmakar',
    full_name: 'Madhuri Karmakar',
    age: 33,
    gender: 'Female',
    village: 'Dholpur',
    phone: '98317 00419',
    bloodGroup: 'B+',
    allergies: 'None reported',
    chronicConditions: 'Polycystic Ovarian Syndrome (PCOS)',
    registeredDate: '2026-02-08',
    lastVisitDate: '2026-08-11',
    totalVisits: 4,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-31',
    clinicId: 'KAY-26-0134',
    external_id: 'KAY-26-0134',
    fullName: 'Jitendra Bagdi',
    full_name: 'Jitendra Bagdi',
    age: 47,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98304 88120',
    bloodGroup: 'AB-',
    allergies: 'None reported',
    chronicConditions: 'Essential Tremor',
    registeredDate: '2025-11-19',
    lastVisitDate: '2026-07-15',
    totalVisits: 5,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-32',
    clinicId: 'KAY-26-0135',
    external_id: 'KAY-26-0135',
    fullName: 'Sarita Besra',
    full_name: 'Sarita Besra',
    age: 25,
    gender: 'Female',
    village: 'Jamunwadi',
    phone: '97323 22901',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-04-05',
    lastVisitDate: '2026-07-28',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-33',
    clinicId: 'KAY-26-0136',
    external_id: 'KAY-26-0136',
    fullName: 'Hemant Gope',
    full_name: 'Hemant Gope',
    age: 36,
    gender: 'Male',
    village: 'Rampur',
    phone: '98729 44109',
    bloodGroup: 'B+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-05-20',
    lastVisitDate: '2026-08-09',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-34',
    clinicId: 'KAY-26-0137',
    external_id: 'KAY-26-0137',
    fullName: 'Kalyani Ghosh',
    full_name: 'Kalyani Ghosh',
    age: 51,
    gender: 'Female',
    village: 'Sundarpur',
    phone: '94339 33012',
    bloodGroup: 'A+',
    allergies: 'Cephalosporins',
    chronicConditions: 'Post-Menopausal Osteopenia',
    registeredDate: '2025-08-01',
    lastVisitDate: '2026-08-22',
    totalVisits: 6,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-35',
    clinicId: 'KAY-26-0138',
    external_id: 'KAY-26-0138',
    fullName: 'Vikas Borde',
    full_name: 'Vikas Borde',
    age: 30,
    gender: 'Male',
    village: 'Wardha',
    phone: '98227 11409',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-06-18',
    lastVisitDate: '2026-08-16',
    totalVisits: 2,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-36',
    clinicId: 'KAY-26-0139',
    external_id: 'KAY-26-0139',
    fullName: 'Mangala Bai',
    full_name: 'Mangala Bai',
    age: 63,
    gender: 'Female',
    village: 'Wardha',
    phone: '98223 55018',
    bloodGroup: 'B-',
    allergies: 'Metronidazole',
    chronicConditions: 'Type 2 Diabetes, Diabetic Retinopathy',
    registeredDate: '2024-10-08',
    lastVisitDate: '2026-09-03',
    totalVisits: 12,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-37',
    clinicId: 'KAY-26-0140',
    external_id: 'KAY-26-0140',
    fullName: 'Anup Kumar Dey',
    full_name: 'Anup Kumar Dey',
    age: 41,
    gender: 'Male',
    village: 'Bilaspur',
    phone: '98307 22091',
    bloodGroup: 'A+',
    allergies: 'None reported',
    chronicConditions: 'Gout / Hyperuricemia',
    registeredDate: '2026-01-19',
    lastVisitDate: '2026-08-04',
    totalVisits: 4,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-38',
    clinicId: 'KAY-26-0141',
    external_id: 'KAY-26-0141',
    fullName: 'Ratna Barman',
    full_name: 'Ratna Barman',
    age: 24,
    gender: 'Female',
    village: 'Sundarpur',
    phone: '94333 99182',
    bloodGroup: 'O+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-07-14',
    lastVisitDate: '2026-08-30',
    totalVisits: 1,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-39',
    clinicId: 'KAY-26-0142',
    external_id: 'KAY-26-0142',
    fullName: 'Babu Lal Marandi',
    full_name: 'Babu Lal Marandi',
    age: 56,
    gender: 'Male',
    village: 'Jamunwadi',
    phone: '97329 88102',
    bloodGroup: 'B+',
    allergies: 'None reported',
    chronicConditions: 'Essential Hypertension',
    registeredDate: '2025-07-29',
    lastVisitDate: '2026-08-27',
    totalVisits: 7,
    synced: true,
    deleted_at: null,
  },
  {
    id: 'pat-40',
    clinicId: 'KAY-26-0143',
    external_id: 'KAY-26-0143',
    fullName: 'Purnima Mallick',
    full_name: 'Purnima Mallick',
    age: 37,
    gender: 'Female',
    village: 'Rampur',
    phone: '98726 00318',
    bloodGroup: 'AB+',
    allergies: 'None reported',
    chronicConditions: 'None',
    registeredDate: '2026-03-08',
    lastVisitDate: '2026-07-19',
    totalVisits: 3,
    synced: true,
    deleted_at: null,
  },
];

export const DEV_VISITS: DbVisit[] = [
  {
    id: 'vis-701',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2026-09-14',
    time: '10:24',
    visit_date: '2026-09-14T10:24:00Z',
    clinicianName: 'Dr. A. Kulkarni',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'CONSULT',
    chiefComplaint: 'Follow-up for hypertension, morning head heaviness and occipital tightness.',
    vitals: {
      bloodPressureSystolic: 128,
      bloodPressureDiastolic: 82,
      pulseBpm: 78,
      tempCelsius: 36.8,
      weightKg: 61,
    },
    diagnosis: 'Stage 1 Essential Hypertension (controlled on medication)',
    prescriptionText: 'Tab Telmisartan 40mg (1-0-0) x 30 days\nTab Metformin 500mg SR (1-0-1) post meals x 30 days',
    prescriptions: [],
    clinicalNotes:
      'Patient reports consistent compliance with antihypertensives over the past 3 months. Morning headaches have reduced in frequency. Salt restriction adherence is good. Fasting glucose profile was reviewed today.',
    attachments: [
      { id: 'att-1', name: 'lab_report_14sep.pdf', type: 'pdf' },
      { id: 'att-2', name: 'prescription_photo.jpg', type: 'image' },
    ],
    synced: true,
    lastModified: '2026-09-14T10:45:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-702',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2026-05-12',
    time: '11:15',
    visit_date: '2026-05-12T11:15:00Z',
    clinicianName: 'Dr. A. Kulkarni',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'LAB',
    chiefComplaint: 'Routine bi-annual biochemical lab evaluation for diabetes and kidney profile.',
    vitals: {
      bloodPressureSystolic: 132,
      bloodPressureDiastolic: 84,
      pulseBpm: 76,
      tempCelsius: 36.6,
      weightKg: 61,
    },
    diagnosis: 'Type 2 Diabetes Mellitus - Lab Review (HbA1c 6.8%)',
    prescriptionText: 'Routine labs completed: Fasting Blood Sugar 114 mg/dL, Post-prandial 148 mg/dL, Serum Creatinine 0.9 mg/dL. Renal profile within normal limits.',
    prescriptions: [],
    clinicalNotes:
      'Biochemical markers stable. Glycemic index shows adequate metabolic control on oral hypoglycemics. Serum creatinine and urine microalbumin show no signs of early nephropathy.',
    attachments: [{ id: 'att-3', name: 'lab_metabolic_panel.pdf', type: 'pdf' }],
    synced: true,
    lastModified: '2026-05-12T11:40:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-703',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2026-03-14',
    time: '09:30',
    visit_date: '2026-03-14T09:30:00Z',
    clinicianName: 'Dr. A. Kulkarni',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'RX',
    chiefComplaint: 'Scheduled refill of maintenance medicines for diabetes and blood pressure.',
    vitals: {
      bloodPressureSystolic: 126,
      bloodPressureDiastolic: 80,
      pulseBpm: 72,
      tempCelsius: 36.7,
      weightKg: 62,
    },
    diagnosis: 'Chronic Disease Maintenance Refill',
    prescriptionText: 'Dispensed 60-day sub-centre supply:\n1. Tab Telmisartan 40mg (1-0-0) #60\n2. Tab Metformin 500mg (1-0-1) #120\n3. Tab Vitamin B-complex daily #60',
    prescriptions: [],
    clinicalNotes:
      'Patient asymptomatic. Blood pressure sitting 126/80 mmHg. No peripheral edema or postural symptoms. Dispensed 2 months of standard NCD drug quota from pharmacy stock.',
    synced: true,
    lastModified: '2026-03-14T09:50:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-704',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2025-11-08',
    time: '14:10',
    visit_date: '2025-11-08T14:10:00Z',
    clinicianName: 'Dr. P. Joshi',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'CONSULT',
    chiefComplaint: 'Acute viral fever, rigors, body ache, and mild dry cough for 3 days.',
    vitals: {
      bloodPressureSystolic: 120,
      bloodPressureDiastolic: 78,
      pulseBpm: 94,
      tempCelsius: 38.4,
      weightKg: 60,
    },
    diagnosis: 'Acute Viral Febrile Illness (Malaria RDT Negative)',
    prescriptionText: 'Tab Paracetamol 650mg (1-1-1) SOS x 4 days\nTab Cetirizine 10mg (0-0-1) x 5 days\nORS packets x 4 sachets',
    prescriptions: [],
    clinicalNotes:
      'Throat mildly congested, chest clear bilaterally. Malaria rapid diagnostic card negative. Note: Patient has documented Penicillin allergy; avoided beta-lactams.',
    synced: true,
    lastModified: '2025-11-08T14:35:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-705',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2024-06-18',
    time: '10:45',
    visit_date: '2024-06-18T10:45:00Z',
    clinicianName: 'Dr. A. Kulkarni',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'CONSULT',
    chiefComplaint: 'Bilateral mild numbness and burning sensation in soles of feet for 2 weeks.',
    vitals: {
      bloodPressureSystolic: 134,
      bloodPressureDiastolic: 86,
      pulseBpm: 80,
      tempCelsius: 36.7,
      weightKg: 63,
    },
    diagnosis: 'Early Diabetic Peripheral Sensory Neuropathy',
    prescriptionText: 'Tab Methylcobalamin + Alpha Lipoic Acid (1-0-0) x 30 days\nContinue Metformin 500mg SR post meals',
    prescriptions: [],
    clinicalNotes:
      'Monofilament test reveals slightly reduced tactile sensation over 1st and 5th metatarsal heads bilaterally. Peripheral pulses palpable. Foot inspection education provided.',
    synced: true,
    lastModified: '2024-06-18T11:10:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-706',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2024-01-10',
    time: '11:20',
    visit_date: '2024-01-10T11:20:00Z',
    clinicianName: 'Dr. S. Rao',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'CONSULT',
    chiefComplaint: 'General check-up, mild lethargy and pallor noticed by ASHA worker.',
    vitals: {
      bloodPressureSystolic: 124,
      bloodPressureDiastolic: 80,
      pulseBpm: 76,
      tempCelsius: 36.5,
      weightKg: 62,
    },
    diagnosis: 'Mild Nutritional Anemia (Hb 10.4 g/dL)',
    prescriptionText: 'Iron & Folic Acid tablets (1 daily after food) x 60 days\nTab Albendazole 400mg stat dose',
    prescriptions: [],
    clinicalNotes:
      'Hemoglobin tested via HemoCue: 10.4 g/dL. Dietary counselling regarding green leafy vegetables and jaggery consumption given. Deworming provided with single dose Albendazole.',
    synced: true,
    lastModified: '2024-01-10T11:45:00Z',
    deleted_at: null,
  },
  {
    id: 'vis-707',
    patientId: 'P-0412',
    patient_id: 'P-0412',
    patientName: 'Sunita Patil',
    patientClinicId: 'P-0412',
    date: '2023-03-14',
    time: '09:15',
    visit_date: '2023-03-14T09:15:00Z',
    clinicianName: 'Dr. A. Kulkarni',
    clinicianRole: 'Doctor',
    status: 'Completed',
    visitType: 'CONSULT',
    chiefComplaint: 'First registration visit. Excessive thirst, frequent nighttime urination, fatigue.',
    vitals: {
      bloodPressureSystolic: 148,
      bloodPressureDiastolic: 92,
      pulseBpm: 84,
      tempCelsius: 36.9,
      weightKg: 64,
    },
    diagnosis: 'New-onset Type 2 Diabetes Mellitus & Stage 1 Hypertension',
    prescriptionText: 'Tab Metformin 500mg (1-0-1) post meals\nTab Telmisartan 40mg (1-0-0) morning\nDiet and lifestyle modification',
    prescriptions: [],
    clinicalNotes:
      'Patient enrolled in NCD register. Random capillary blood glucose measured at 242 mg/dL. BP measured twice: 148/92 mmHg. Flagged Penicillin allergy prominently.',
    synced: true,
    lastModified: '2023-03-14T10:00:00Z',
    deleted_at: null,
  },
];

export const DEV_PRESCRIPTIONS: Prescription[] = [
  // vis-701
  {
    id: 'rx-1',
    visit_id: 'vis-701',
    medication: 'Telmisartan',
    medicine: 'Telmisartan',
    dosage: '40mg',
    dose: '40mg',
    frequency: '1-0-0',
    durationDays: 30,
    duration_value: 30,
    position: 0,
    deleted_at: null,
  },
  {
    id: 'rx-2',
    visit_id: 'vis-701',
    medication: 'Metformin SR',
    medicine: 'Metformin SR',
    dosage: '500mg',
    dose: '500mg',
    frequency: '1-0-1',
    durationDays: 30,
    duration_value: 30,
    position: 1,
    deleted_at: null,
  },
  // vis-703
  {
    id: 'rx-3',
    visit_id: 'vis-703',
    medication: 'Telmisartan 40mg',
    medicine: 'Telmisartan 40mg',
    dosage: '40mg',
    dose: '40mg',
    frequency: 'Once daily',
    durationDays: 60,
    duration_value: 60,
    position: 0,
    deleted_at: null,
  },
  {
    id: 'rx-4',
    visit_id: 'vis-703',
    medication: 'Metformin 500mg',
    medicine: 'Metformin 500mg',
    dosage: '500mg',
    dose: '500mg',
    frequency: 'Twice daily',
    durationDays: 60,
    duration_value: 60,
    position: 1,
    deleted_at: null,
  },
  // vis-704
  {
    id: 'rx-5',
    visit_id: 'vis-704',
    medication: 'Paracetamol',
    medicine: 'Paracetamol',
    dosage: '650mg',
    dose: '650mg',
    frequency: 'TID SOS',
    durationDays: 4,
    duration_value: 4,
    position: 0,
    deleted_at: null,
  },
  {
    id: 'rx-6',
    visit_id: 'vis-704',
    medication: 'Cetirizine',
    medicine: 'Cetirizine',
    dosage: '10mg',
    dose: '10mg',
    frequency: 'OD HS',
    durationDays: 5,
    duration_value: 5,
    position: 1,
    deleted_at: null,
  },
  // vis-705
  {
    id: 'rx-7',
    visit_id: 'vis-705',
    medication: 'Methylcobalamin combo',
    medicine: 'Methylcobalamin combo',
    dosage: '1500mcg',
    dose: '1500mcg',
    frequency: 'OD',
    durationDays: 30,
    duration_value: 30,
    position: 0,
    deleted_at: null,
  },
  // vis-706
  {
    id: 'rx-8',
    visit_id: 'vis-706',
    medication: 'IFA Tablet',
    medicine: 'IFA Tablet',
    dosage: '100mg elemental iron',
    dose: '100mg elemental iron',
    frequency: 'OD',
    durationDays: 60,
    duration_value: 60,
    position: 0,
    deleted_at: null,
  },
  {
    id: 'rx-9',
    visit_id: 'vis-706',
    medication: 'Albendazole',
    medicine: 'Albendazole',
    dosage: '400mg',
    dose: '400mg',
    frequency: 'Stat',
    durationDays: 1,
    duration_value: 1,
    position: 1,
    deleted_at: null,
  },
  // vis-707
  {
    id: 'rx-10',
    visit_id: 'vis-707',
    medication: 'Metformin',
    medicine: 'Metformin',
    dosage: '500mg',
    dose: '500mg',
    frequency: 'BID',
    durationDays: 30,
    duration_value: 30,
    position: 0,
    deleted_at: null,
  },
  {
    id: 'rx-11',
    visit_id: 'vis-707',
    medication: 'Telmisartan',
    medicine: 'Telmisartan',
    dosage: '40mg',
    dose: '40mg',
    frequency: 'OD',
    durationDays: 30,
    duration_value: 30,
    position: 1,
    deleted_at: null,
  },
];

export async function seedDevDatabase(): Promise<void> {
  const count = await db.patients.count();
  if (count === 0) {
    console.log('[Dexie DevSeed] Populating clinic, staff, patients, visits, prescriptions, attachments…');
    await db.transaction('rw', [db.clinics, db.users, db.patients, db.visits, db.prescriptions, db.attachments], async () => {
      // 1. Clinic
      await db.clinics.put({
        id: 'cln-wardha-01',
        name: 'Kaya Rural Clinic',
        facility_code: 'MH-WRD-0142',
        district: 'Wardha',
        state: 'Maharashtra',
      });

      // 2. Staff users
      await db.users.bulkPut([
        {
          id: 'usr-default-01',
          clinic_id: 'cln-wardha-01',
          role: 'Admin',
          full_name: 'Dr. Amina Khan',
          email: 'amina.k@clinic.kaya',
        },
        {
          id: 'usr-staff-02',
          clinic_id: 'cln-wardha-01',
          role: 'Clinician',
          full_name: 'Nurse S. Meshram',
          email: 's.meshram@kaya.health',
        },
        {
          id: 'usr-staff-03',
          clinic_id: 'cln-wardha-01',
          role: 'Health worker',
          full_name: 'R. Yadav',
          email: 'r.yadav@kaya.health',
        },
      ]);

      // 3. Patients
      await db.patients.bulkPut(DEV_PATIENTS);

      // 4. Visits
      await db.visits.bulkPut(DEV_VISITS);

      // 5. Prescriptions
      await db.prescriptions.bulkPut(DEV_PRESCRIPTIONS);

      // 6. Attachments
      await db.attachments.bulkPut([
        {
          id: 'att-dev-01',
          clinic_id: 'cln-wardha-01',
          patient_id: 'P-0412',
          visit_id: 'vis-701',
          filename: 'Lipid_Panel_Report.pdf',
          file_size: 145000,
          mime_type: 'application/pdf',
          sha256: 'sha-sample-lipid-701',
          ocr_status: 'ready',
          ocr_text: 'Lipid Panel Report: Total Cholesterol: 184 mg/dL\nTriglycerides: 142 mg/dL\nHDL: 46 mg/dL\nLDL: 110 mg/dL',
          ocr_confidence: 0.96,
          sync_state: 'synced',
          created_at: '2026-09-14T10:30:00Z',
        },
        {
          id: 'att-dev-02',
          clinic_id: 'cln-wardha-01',
          patient_id: 'P-0412',
          visit_id: 'vis-702',
          filename: 'ECG_Tracing_Rhythm.jpg',
          file_size: 280000,
          mime_type: 'image/jpeg',
          sha256: 'sha-sample-ecg-702',
          ocr_status: 'ready',
          ocr_text: 'ECG Report: Normal sinus rhythm. Heart rate 76 bpm. PR interval 150 ms. QRS duration 86 ms. No acute ST-T changes.',
          ocr_confidence: 0.94,
          sync_state: 'synced',
          created_at: '2026-09-02T14:15:00Z',
        },
      ]);
    });
    console.log('[Dexie DevSeed] Complete.');
  }
}
